# Cấu hình chính cho Mobile Automation Project

# Appium Server
appium:
  host: "127.0.0.1"
  port: 4723
  path: "/wd/hub"
  timeout: 60

# Mobile App Configuration
app:
  android:
    platformName: "Android"
    automationName: "UiAutomator2"
    deviceName: "Android"
    platformVersion: "12.0"
    appPackage: "net.citigo.kiotviet.touch"
    appActivity: "net.citigo.kiotviet.ui.SplashScreenActivity"
    noReset: false
    fullReset: true
    
  ios:
    platformName: "iOS"
    automationName: "XCUITest"
    deviceName: "iPhone Simulator"
    platformVersion: "15.0"
    app: "${EXECDIR}/apps/sample-app.app"
    noReset: false
    fullReset: true

# Test Configuration
test:
  timeout:
    implicit: 10
    explicit: 20
    pageLoad: 30
    
  retry:
    max_attempts: 3
    delay: 2
    
  screenshot:
    on_failure: true
    on_success: false
    directory: "screenshots"
    
  video:
    record: false
    directory: "videos"

# Environment Configuration
environments:
  dev:
    base_url: "https://dev-api.example.com"
    username: "testuser"
    password: "testpass"
    
  staging:
    base_url: "https://staging-api.example.com"
    username: "staginguser"
    password: "stagingpass"
    
  prod:
    base_url: "https://api.example.com"
    username: "produser"
    password: "prodpass"

# Reporting
reporting:
  allure:
    enabled: true
    results_dir: "reports/allure-results"
    report_dir: "reports/allure-report"
    
  robot:
    enabled: true
    output_dir: "reports"
    
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: "test@example.com"
    sender_password: "password"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/automation.log"
  max_size: "10MB"
  backup_count: 5 